version: '3.8'

services:
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_USER: phat
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: Test2
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - pynetwork

  fe:
    build: ./fe
    restart: always
    depends_on:
      - be
    links:
      - be
    ports:
      - "5503:8080"

    volumes:
      - ./fe:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - pynetwork

  be:
    build: ./be
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: Test2
      MYSQL_USER: phat
      MYSQL_PASSWORD: 123456
    ports:
      - "5002:5000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./be:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 30s
      timeout: 3s
      retries: 5
    networks:
      - pynetwork

networks:
  pynetwork:
    driver: bridge
    external: true
